module.exports={
    userFormarteError:{
        code:'400',
        message:'用户名或密码为空',
        result:''
    },
    userIsExited:{
        code:'400',
        message:'用户名已存在',
        result:''
    },
    useRegisterErr:{
        code:'400',
        message:'注册发生错误',
        result:''
    },
    useLoginErr:{
        code:'400',
        message:'密码错误',
        result:''
    },
    tokenexpirederr:{
        code:'403',
        message:'token错误',
        result:''
    },
    updateError:{
        code:'400',
        message:'更新失败',
        result:''
    },
    NotAdminPermission:{
        code:'407',
        message:'没有管理员权限',
        result:''
    },
    updateGoodsError:{
        code:'400',
        message:'更新商品失败',
        result:''
    },
    GoodsError:{
        code:'400',
        message:'获取商品失败',
        result:''
    },
    BlackError:{
        code:'400',
        message:'商品已下架',
        result:''
    },
    addressError: {
        code:'400',
        message:'地址错误',
        result:''
    }
    
}